---
- name: Install Prometheus and Grafana
  hosts: all
  become: true
  become_user: root
  vars:
    prometheus_version: 2.23.0
    grafana_version: 7.5.2
  tasks:
  - name: Install dependencies
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - wget
      - tar
      - curl

  - name: Add specified repository into sources list
    ansible.builtin.apt_repository:
      repo: deb http://archive.canonical.com/ubuntu hardy partner
      state: present

  - name: Install grafana
    apt:
      name: grafana={{ grafana_version }}
      state: present

  - name: Create Grafana user
    user:
      name: grafana
      group: grafana
      home: /opt/grafana-{{ grafana_version }}.linux-amd64
      shell: /sbin/nologin
      createhome: yes

  - name: Change ownership of grafana directory
    file:
      path: /opt/grafana-{{ grafana_version }}.linux-amd64
      owner: grafana
      group: grafana
      mode: '0755'

  - name: Create grafana configuration directory
    file:
      path: /etc/grafana
      owner: grafana
      group: grafana
      mode: '0755'
      state: directory

  - name: Copy Grafana configuration file
    template:
      src: templates/grafana.ini.j2
      dest: /etc/grafana/grafana.yml
      owner: grafana
      group: grafana
      mode: '0644'

  - name: Enable and start grafana service
    systemd:
      name: grafana
      state: started
      enabled: yes

  - name: Install Promotheus
    apt:
      name: prometheus={{ prometheus_version }}
      state: present

  - name: Create Prometheus user
    user:
      name: prometheus
      group: prometheus
      home: /opt/prometheus-{{ prometheus_version }}.linux-amd64
      shell: /sbin/nologin
      createhome: yes

  - name: Change ownership of Prometheus directory
    file:
      path: /opt/prometheus-{{ prometheus_version }}.linux-amd64
      owner: prometheus
      group: prometheus
      mode: '0755'

  - name: Create Prometheus configuration directory
    file:
      path: /etc/prometheus
      owner: prometheus
      group: prometheus
      mode: '0755'
      state: directory

  - name: Copy Prometheus configuration file
    template:
      src: templates/prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
      owner: prometheus
      group: prometheus
      mode: '0644'

  - name: Enable and start Prometheus service
    systemd:
      name: prometheus
      state: started
      enabled: yes
